[package]
name = "driver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = {workspace = true}
async-trait = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
uuid = {workspace = true }
chrono = {workspace = true}